# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: manual packaging

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: false
        default: '6.9.454'


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v2
      with:
        java-version: '12'
        distribution: 'adopt'
        server-id: spirit-nexus # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_USERNAME # env variable for username in deploy
        server-password: MAVEN_PASSWORD # env variable for token in deploy

    - name: Echo version Reference
      run: echo ${{ github.event.inputs.version }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy
      env:
        MAVEN_USERNAME: github
        MAVEN_PASSWORD: ${{ secrets.NEXUS_DEPLOY_PASSWORD }}
